### ISSUE TITLE
AWS Toolkit does not pick up the template.yaml in Local Function Configuration

### ISSUE THREAD

**Issue by aluciffer** [aws/aws-toolkit-jetbrains#1262]
**Describe the bug**
When i create a new local function or 'Edit Configurations' for a local AWS function, if i check the box 'From Template' and browse for my **template.yaml** file, AWS Toolkit does not see it (the OK button does not get activated).

My workaround for the moment is to hardcode (paste the full file address) including the template.yaml filename in the box. Press OK. Then open the window again to be able to choose from the defined resources a.s.o.

**To reproduce**
1. Choose Run -> Edit Configurations
2. Choose AWS Lambda from the left-side, and press the PLUS sign to add a new local function.
3. Check the 'From Template' checkbox and browse for the template.yaml

**Expected behavior**
The template.yaml in the selected directory be identified, and the OK button gets active

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/3103030/66747669-c2f2c400-ee8d-11e9-936e-204b7289a437.png)
![Untitled 2](https://user-images.githubusercontent.com/3103030/66747670-c2f2c400-ee8d-11e9-8a74-a181b82406a3.png)

**Your Environment**
 - OS: Windows 10 Pro
 - JetBrains' Product: PyCharm 2019.2.2 (Community Edition)
Build #PC-192.6603.34, built on September 10, 2019
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 976M
Cores: 8
Registry: 
Non-Bundled Plugins: AWSCloudFormation, aws.toolkit, ru.meanmail.plugin.requirements
 - JetBrains' Product Version:
 - Toolkit Version: 1.6
 - SAM CLI Version: --
 - JVM/Python Version: 3.7

**Comment by abrooksv** [comment]
Need to replicate this, but a quick scan through the code seems to indicate that JetBrains' YAML file type is defined using the extension ".yml".

**Comment by abrooksv** [comment]
Not able to replicate this:
<img width="276" alt="Screen Shot 2019-10-14 at 10 49 21 AM" src="https://user-images.githubusercontent.com/8992246/66771907-54533d80-ee70-11e9-84aa-bd2101071c41.png">

You may need to refresh the folder by clicking the refresh icon in the file browser toolbar

**Comment by abrooksv** [comment]
You need to select the file itself, not the containing folder

**Comment by aluciffer** [comment]
Hi Abrooksv, thank you for your implication, 
I am able to replicate this, and if i should pick the file itself, then there are two problems:
1. Semantics: The title of the window specifies : **Select Path** and not "_File_"
2. Please see the attached file, do you see any template.yaml that i could select? As in the previous attachment, there is a valid template.yaml in the directory, which i am able to hard-code, and by which i can repeatedly connect and successfully deploy.

Do you see any obstacles or impediments that could prevent seeing my file?

**Comment by aluciffer** [comment]
Oh ok, i've also renamed the file to .yml, and there's no difference there.

**Comment by abrooksv** [comment]
I can't see it in your screenshot. It would be below all the child folders of "untitlted2" folder since JetBrains puts folders before files in the file chooser dialog.

To comment 1 about the name, we can rename that to say "Select Template File" if you think that would have clarified it for you.

**Comment by aluciffer** [comment]
I have tried various tests, and this is what i've found:
As soon as i append any of the following two lines **above** the **Resources** section, the file is not seen in the selected path.
As soon as i move any of the two lines **below** the **Resources** section, the 'Path' selection sees the file , and i can select it.

```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
```

For the window title, yes, 'File' would mean to select the file, while 'Path', in my understanding, can include multiple files. Or maybe i'm wrong!?
 

![Untitled 2](https://user-images.githubusercontent.com/3103030/67464355-e0711c00-f64b-11e9-892d-a5760bef0f59.png)
![Untitled](https://user-images.githubusercontent.com/3103030/67464356-e0711c00-f64b-11e9-9b81-942631da912f.png)

**Comment by abrooksv** [comment]
I tried this template, and I could not reproduce it:
```
Description: >
  AWS

  Sample SAM Template for AWS
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```
