### ISSUE TITLE
Error: Cannot find handler 'index.handler' in project

### ISSUE THREAD

**Issue by kkor** [aws/aws-toolkit-jetbrains#2050]
**Your Environment**

- OS: MacOs
- JetBrains product: Webstorm
- JetBrains product version: 2020.2.1
- AWS Toolkit version: aws-cli/2.0.46 
- SAM CLI version: 1.2.0
- JVM/Python version: Python/3.7.4

**Question**

I have an existing Serverless SAM project with typescript setup by someone else. If I click the play button in the gutter in the root template.yml, I can choose in the popup "from template" > "NameOfTheFunction", but then I get on the bottom on the pop the error "Error: Cannot find handler 'index.handler' in project".

The template.yml has a global function like this:
```
Globals:
    Function:
        Handler: index.handler
        Runtime: nodejs12.x
        Timeout: 15
```

Any pointers on what might be missing here?
