### ISSUE TITLE
failed to enable debugging on ECS service when enabling Cloud Debugging

### ISSUE THREAD

**Issue by damnhandy** [aws/aws-toolkit-jetbrains#2097]
**Describe the bug**
After following the instructions in the [Debugging code in ECS Fargate doc](https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/ecs-debug.html),  I created the required policy and associated the `AmazonSSMManagedInstanceCore` managed policy to my services role. When I attempt to Enable Cloud Debugging, the dialog pops up showing the correct role that has the correct permissions enabled. Once I click "OK" everything looks good until it gets to the end. This is what I get:

```
The 'arn:aws:ecs:us-east-1:123456789000:task-definition/demo:35' task definition is already enabled for debugging: 'arn:aws:ecs:us-east-1:123456789000:task-definition/cloud-debug-demo:1'
Checking if service in cluster 'demo' with name 'Demo-app-regional-ecs-Service-1L7Q3TXTKHKE0' is associated to a load balancer
Service in cluster 'demo' with name 'Demo-app-regional-ecs-Service-1L7Q3TXTKHKE0' is associated to a load balancer, proceeding to target group cloning
Cloning target group. New target group configuration is '{
  HealthCheckEnabled: true,
  HealthCheckIntervalSeconds: 10,
  HealthCheckPath: "/ping",
  HealthCheckPort: "8080",
  HealthCheckProtocol: "HTTP",
  HealthyThresholdCount: 4,
  Name: "cloud-debug-demo",
  Port: 8443,
  Protocol: "TCP",
  TargetType: "ip",
  VpcId: "vpc-00000000000000000"
}'
https://elasticloadbalancing.us-east-1.amazonaws.com (elasticloadbalancing:CreateTargetGroup) called with b2c41fc5-fc14-4dc4-acbc-4acb44325032 ; status: "InvalidConfigurationRequest: Health check healthy threshold and unhealthy threshold must be the same for target groups with the TCP protocol\n\tstatus code: 400, request id: b2c41fc5-fc14-4dc4-acbc-4acb44325032"
Publishing Metrics: '{cmd_service 2020-09-24T14:24:47.698144-04:00 {123456789000 1.0.357} [{Success 0 Count} {Failure 1 Count} {Duration 6.8636483e+09 Milliseconds}]}'
Telemetry endpoint response Status: '200 OK'
errors":["failed to enable debugging on ECS service name='Demo-app-regional-ecs-Service-1L7Q3TXTKHKE0', cluster='demo' with iamRole='arn:aws:iam::123456789000:role/payments.aws.cde-dev.demo-service', debugEntrypoint='' and restartCmd=''","enabling debugging session failed for the service 'Demo-app-regional-ecs-Service-1L7Q3TXTKHKE0' in cluster 'demo'","unable to clone the target group with ARN 'arn:aws:elasticloadbalancing:us-east-1:123456789000:targetgroup/demo/dd7fa0e6c7612a5d'","Health check healthy threshold and unhealthy threshold must be the same for target groups with the TCP protocol"]}
Error details:
	- failed to enable debugging on ECS service name='Demo-app-regional-ecs-Service-1L7Q3TXTKHKE0', cluster='demo' with iamRole='arn:aws:iam::123456789000:role/payments.aws.cde-dev.demo-service', debugEntrypoint='' and restartCmd=''
	- enabling debugging session failed for the service 'Demo-app-regional-ecs-Service-1L7Q3TXTKHKE0' in cluster 'demo'
	- unable to clone the target group with ARN 'arn:aws:elasticloadbalancing:us-east-1:123456789000:targetgroup/demo/dd7fa0e6c7612a5d'
	- Health check healthy threshold and unhealthy threshold must be the same for target groups with the TCP protocol
```
The error comes back immediately as if nothing was even attempted. The services in the account are somewhat locked down and we have a combination of NACLs and Security Groups in play, so I am not sure if there are some ports or IPs that need to be abled here? In my CloudFormation, the heathy and unhealthy thresholds are the same:

```yaml
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Ref LoadBalancerName
      VpcId: !Ref VpcId
      Port: 8443
      TargetType: 'ip'
      Protocol: TCP
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: '/ping'
      HealthCheckPort: '8080'
      HealthCheckProtocol: 'HTTP'
      HealthCheckTimeoutSeconds: 6
      HealthyThresholdCount: 4
      UnhealthyThresholdCount: 4
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 5 # seconds
        - Key: proxy_protocol_v2.enabled
          Value: false
```

**To reproduce**
See above. 

**Expected behavior**
Cloud Debugging to be enabled or some more helpful hints in the error responses that might indicate how to resolve the issue. 

**Screenshots**

**Your Environment**
- OS: macOS Catalina 10.15.6
- JetBrains product: IntelliJ IDEA
- JetBrains product version: 2020.2.2
- AWS Toolkit version: 1.18-202
- JVM/Python version: AdoptOpenJDK 11.0.8

**Additional context**

Other interesting notes: the only way for the applications in this account to gain outbound access is via a forward proxy.  We do leverage private endpoints where possible. Is the forward proxy getting in the way here? Or is there a specific set of ports that need to opened? Does the Cloud Debugger even work behind a forward proxy?
