### ISSUE TITLE
Running Quarkus Amazon Lambda causes Cannot find handler

### ISSUE THREAD

**Issue by tchlyah** [aws/aws-toolkit-jetbrains#2168]
**Describe the bug**
When trying to run or debug a [Quarkus Amazon Lambda](https://quarkus.io/guides/amazon-lambda), either by using [QuarkusStreamHandler](https://github.com/quarkusio/quarkus/blob/master/extensions/amazon-lambda/runtime/src/main/java/io/quarkus/amazon/lambda/runtime/QuarkusStreamHandler.java), or from the produced template file `sam.jvm.yaml`, it refuses to run cause of the **Error: Cannot find handler 'io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest' in project.**

**To reproduce**
1. Use example here: [aws-quarkus-demo/lambda](https://github.com/aws-samples/aws-quarkus-demo/tree/master/lambda)
2. Add run configuration (AWS Lambda -> Local)
3. Either set From template referencing the file `target/sam.jvm.yaml`, or set the Handler to `io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest`.
=> `Error: Cannot find handler 'io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest' in project.`

Running the default handler [com.amazon.example.ProcessingLambda](https://github.com/aws-samples/aws-quarkus-demo/blob/master/lambda/src/main/java/com/amazon/example/ProcessingLambda.java) won't work because it doesn't support Quarkus CDI.

**Expected behavior**
Since the [QuarkusStreamHandler](https://github.com/quarkusio/quarkus/blob/master/extensions/amazon-lambda/runtime/src/main/java/io/quarkus/amazon/lambda/runtime/QuarkusStreamHandler.java) is in the classpath, it should accept it and run the function.

**Screenshots**
<img width="1072" alt="Capture d’écran 2020-10-23 à 11 06 06" src="https://user-images.githubusercontent.com/3661112/96980769-c0569000-151f-11eb-9e2f-844866c48bb2.png">

**Your Environment**
- OS: MacOS Catalina 10.15.7
- JetBrains product: Intellij idea 
- JetBrains product version: 2020.2.3
- AWS Toolkit version: 1.20-202
- SAM CLI version: 1.6.2
- JVM/Python version: 11

**Additional context**
`sam.jvm.yaml`:
```yaml
  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus - 1.0.0-SNAPSHOT
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    MeasurementsFeeder:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java11
        CodeUri: function.zip
        MemorySize: 256
        Timeout: 15
        Policies: AWSLambdaBasicExecutionRole
```
