### ISSUE TITLE
helloworld—outputs—ServerlessRestApi

### ISSUE THREAD

**Issue by autohandle** [aws/aws-toolkit-jetbrains#2695]
**Question**

in the HelloWorld template, the Outputs section references: ServerlessRestApi & AWS::Region.

i know what it is referencing, but i can't find where these pseudo-variables are documented/listed?

oh, and if one of these variables is used along with say an intrinsic function, how do you print them out for debugging (use them in an environment variable & then do a printenv inside the lambda?)

**Comment by abrooksv** [comment]
Are you referring to these?

```
Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```

`AWS::Region` is the AWS region the stack is deployed in: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-region

https://github.com/aws/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api talks about the `ServerlessRestApi`

As for debugging, I use env var printing like you said, or output them as an Output and view it in the AWS console or the Outputs tab in the IDE

![Screen Shot 2021-06-30 at 12 05 53 PM](https://user-images.githubusercontent.com/8992246/124017411-89ccf100-d99b-11eb-9d2f-4d3f8e38fb29.png)
