### ISSUE TITLE
Local AWS Lambda Run/Debug Configuration: Error: The runtime 'nodejs16.x' is unsupported.

### ISSUE THREAD

**Issue by jcrivelloia** [aws/aws-toolkit-jetbrains#3192]
When I create a Run/Debug Configuration of type _AWS Lambda/Local_ and configure it _From template_ for a template that uses the nodejs16.x runtime, I receive the error: `The runtime 'nodejs16.x' is unsupported.`

1. Use the `template.yaml` file that I included below.
2. Open the Run/Debug Configurations dialog.
3. Click the "+" button.
4. Click "AWS Lambda/Local".
5. Under the "Configuration" tab select "From template" and the "TestFunction".
6. Accept all other defaults and click Apply.

```yaml
Transform: AWS::Serverless-2016-10-31
Description: REDACTED

Globals:
  Function:
    Runtime: nodejs16.x
    Handler: index.handler
    Architectures:
      - arm64

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/index.zip
      Events:
        EveryMorning:
          Type: Schedule
          Properties:
            Schedule: cron(45 9 * * ? *)
```

**Expected behavior**
I would expect Node 16 to be supported. It works fine with the `sam local invoke` command and it has been supported for a while now.

**Screenshots**
![image](https://user-images.githubusercontent.com/53105438/175834785-2ee70afa-4771-42c0-a637-7cd07d280ae7.png)

**Your Environment**
- OS: macOS Monterey 12.4
- JetBrains product: WebStorm
- JetBrains product version: 2022.1.3
- AWS Toolkit version: 1.45-221
- SAM CLI version: SAM CLI, version 1.51.0
- JVM/Python version: 

```
Build #WS-221.5921.27, built on June 21, 2022

Runtime version: 11.0.15+10-b2043.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

```sh
% brew deps --tree --installed aws/tap/aws-sam-cli
aws/tap/aws-sam-cli
└── python@3.8
    ├── gdbm
    ├── mpdecimal
    ├── openssl@1.1
    │   └── ca-certificates
    ├── readline
    ├── sqlite
    │   └── readline
    ├── tcl-tk
    │   └── openssl@1.1
    │       └── ca-certificates
    └── xz
```

**Additional context**
