### ISSUE TITLE
Cannot debug local Lambda Layer code

### ISSUE THREAD

**Issue by m-crescentini** [aws/aws-toolkit-jetbrains#3261]
**Describe the bug**
This could be similar to [this solved issue](https://github.com/aws/aws-toolkit-jetbrains/issues/908).
I have a standard CloudFormation (no SAM) with a Lambda function (Python 3.9) and a custom local Lambda Layer.

```
GetCommunicationLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      ...
      Code: "../../src/lambda_get_communication"
      Layers:
        - Ref: MyCustomLayer
        ...
     ...

MyCustomLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content: "../../src/layers/my_custom_layer"
      Description: Layer with common utilities
      ...
```

Whenever I put a breakpoint inside the layer code and I start debugging the Lambda function, the console logs this error:

`pydev debugger: warning: trying to add breakpoint to file that does not exist /var/task/d:/lavoro/sviluppo/git/xx/yy/aa-bb-cc/src/layers/my_custom_layer/python/single_dispatch_query.py (will have no effect)`

I am able to debug the Lambda function code as expected, but as soon as I get to the local layer code call, the debugger does not go into the layer file and the breakpoint is skipped. If I debug step-by-step, I can see the variable values updating while the layer code executes.

I enabled IntelliJ debug logs and found this line:

`s.a.t.j.s.PathMapper - Failed to map D:/Lavoro/Sviluppo/Git/xx/yy/aa-bb-cc/src/layers/my_custom_layer/python/single_dispatch_query.py to remote file system: [PathMapping(localRoot='d:/lavoro/sviluppo/git/xx/yy/aa-bb-cc/src/lambda_get_communication/', remoteRoot='/var/task/'), PathMapping(localRoot='d:/lavoro/sviluppo/git/xx/yy/aa-bb-cc/infrastructure/aws-cf/.aws-sam/build/getcommunicationlambdafunction/', remoteRoot='/var/task/'), PathMapping(localRoot='c:/users/m.crescentini/appdata/roaming/jetbrains/intellijidea2022.2/plugins/python/helpers/pydev/', remoteRoot='/tmp/lambci_debug_files/')]`

**To reproduce**
1. Define a Lambda function with a local layer in the CloudFormation template like the one above
2. Start debugging the Lambda function
3. The Python debugger will not enter into the layer file and will skip the breakpoint 

**Expected behavior**
Python debugger goes into the local layer file and stops on the breakpoint.

**Your Environment**
- OS: Windows 10 Pro
- JetBrains product: IntelliJ IDEA 
- JetBrains product version: 2022.2 Ultimate
- AWS Toolkit version: 1.49-222
- SAM CLI version: 1.53
- JVM/Python version: Python 3.9

Thank you.
