### ISSUE TITLE
Local Lambda Running with template.yaml Runtime not working with 'provided' configuration

### ISSUE THREAD

**Issue by slimnader** [aws/aws-toolkit-jetbrains#3408]
**Describe the bug**

When trying to run local lambda as template, 
![image](https://user-images.githubusercontent.com/35436026/206883228-1b690c46-3f2f-4616-acfa-eb1c020c6c29.png)
cant use provided runtime. Need to run with java graalvm-22.1.0+java17 for quarkus native. 

![image](https://user-images.githubusercontent.com/35436026/206883055-06105b3a-3580-4c97-9d0a-eb82da121d74.png)
```
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 380
      MemorySize: 2048
      Handler: com.sunrun.pricing.cache.aws.FindByProposalIdFn::handleRequest
      CodeUri: /
      Runtime: provided #<-- issue here
      Architectures:
        - arm64
    Metadata:
      BuildMethod: makefile
```

**Expected behavior**

Choosing run anyway should atleast invoke the run or debug tabs. Instead it just parrots the error message 

**Your Environment**
- OS:  MacOS
- JetBrains product: Intellij Ultimate
- JetBrains product version: 2022.2.2
- AWS Toolkit version: 1.56
- SAM CLI version: 1.66
- JVM/Python version:

**Additional context**
