### ISSUE TITLE
[3] Python handlers are different between SAM and IDE

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-toolkit-jetbrains#372]
SAM / CloudFormation templates use both `CodeURI` and `Handler` to determine the content root for a given Lambda function. PyCharm has different logic for determining the content roots and the discrepancy means that PyCharm can't find 'valid' Lambda handlers. For example a project with the following structure:

```
./
|-- src/
|    |-- __init__.py
|    |-- app.py (containing def lambda_hander(): method)
|-- template.yaml
```

And a template as follows:
```yaml
Resources:
  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/app.lambda_handler
      Runtime: python3.6
      CodeUri: .
```

SAM assumes that the content root for the function is `./src` and that the intended root directory for the `zip` is `.`; however by virtue for the fact that the `./src` directory contains an `__init__.py` file - PyCharm assumes that `./src` is actually a *module* rather than a regular source directory.

#### Required Changes
For SAM projects, PyCharm's "source root" logic needs to be updated to correctly mark source roots as those directories that are a concatenation of `CodeUri` and `Handler`'s prefix (ie before the last `/` slash).

Additionally the handler logic needs to be updated to include the src directory in the handler based on the modules' relative position to the `CodeUri` for the given function.
