### ISSUE TITLE
Local Lambda Invocation Fails with Unsupported Node.js 22.x Runtime

### ISSUE THREAD

**Issue by liam-bh** [aws/aws-toolkit-jetbrains#5738]
**Describe the bug**
When invoking an AWS SAM template with a Lambda using `Runtime: nodejs22.x` for local debugging, the operation fails with an error: `'The runtime nodejs22.x is not supported'`.

```yaml
Resources:
  appname:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      MemorySize: 128
      Timeout: 120
      Handler: index.handler
      Runtime: nodejs22.x  # Problematic runtime
```

**To Reproduce**
1. Create a SAM template YAML file specifying `Runtime: nodejs22.x` for a Lambda function, or download a generated configuration with this runtime.
2. In your IDE (e.g., WebStorm), click the play/debug arrow for the Lambda resource.
3. Observe the error: `'The runtime nodejs22.x is not supported'`.

**Expected Behavior**
The AWS Toolkit should generate the correct debug configuration for the IDE (WebStorm, in this case) and start execution. This works as expected in AWS Toolkit for VSCode.

**Environment**
- OS: macOS 15.4.1
- IDE: WebStorm
- IDE Version: WS-251.25410.117
- AWS Toolkit Version: 3.71-251
- SAM CLI Version: 1.138.0
- JVM/Python Version: None / 3.9.6 (?)

**Additional Context**
- [SAM CLI PR adding nodejs22 support](https://github.com/aws/aws-sam-cli/pull/7747)
- [AWS Toolkit JetBrains PR upgrading Node to 20](https://github.com/aws/aws-toolkit-jetbrains/pull/4015/files)
- [AWS announcement: Node.js 22 runtime available in Lambda](https://aws.amazon.com/blogs/compute/node-js-22-runtime-now-available-in-aws-lambda/)

**Screenshots**
