### ISSUE TITLE
IntelliJ Ultimate: Cannot find handler "index.handler" 

### ISSUE THREAD

**Issue by MichaelHindley** [aws/aws-toolkit-jetbrains#930]
Given this `template.yml`

```yml
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  TestFunction:
    # This resource creates a Lambda function.
    Type: 'AWS::Serverless::Function'
    Properties:
      # This function uses the Nodejs v6.10 runtime.
      Runtime: nodejs8.10
      # This is the Lambda function's handler.
      Handler: index.handler
      # The location of the Lambda function code
      CodeUri: .
```

and this `index.js`

```javascript
exports.handler = async (event) => {
    console.log(`Processing event ${JSON.stringify(event, null, 2)}`);
    return;
};

```
With `template.yml` and `index.js` in the same folder `lib` that is marked as `source root`.
```
lib marked as source root
lib\template.yml
lib\index.js
```

When I click this button:
![image](https://user-images.githubusercontent.com/1016639/56731295-70e0a980-675a-11e9-8669-b89a6ade6ff2.png)

I expect to be able to execute the lambda, instead, I get:

![image](https://user-images.githubusercontent.com/1016639/56731359-95d51c80-675a-11e9-878a-2acf5de15a69.png)

**Your Environment**
 - OS: Windows 10
 - JetBrains' Product: IntelliJ ultimate
 - JetBrains' Product Version:  2019.1
 - Toolkit Version: 1.3-EAP.2019.04.17
 - SAM CLI Version: 0.15.0
 - JVM/Python Version: ?
