### ISSUE TITLE
Globals Runtime and Handler raise a java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by sam1902** [aws/aws-toolkit-jetbrains#941]
**Describe the bug**

> update failed for AnAction(com.intellij.execution.ExecutorRegistryImpl$ExecutorAction) with ID=Debug

The IDE reports a "Fatal Error" from an exception in the AWS Toolkit (1.3) plugin.
c.f. [induced.txt](https://github.com/aws/aws-toolkit-jetbrains/files/3137597/induced.txt) and [stacktrace.txt](https://github.com/aws/aws-toolkit-jetbrains/files/3137598/stacktrace.txt)

**To reproduce**
1. Create a new Python project
2. In the template file, set the `Globals` to something like that:
```yaml
Globals:
  Function:
    Runtime: python3.7
    Handler: app.lambda_handler
    Timeout: 180
```
3. Delete the `Handler` and `Runtime` from the individual lambda resource(s).
For instance, the default `HelloWorldFunction` would look like that:
```yaml
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
```

N.B. This also breaks if you put only `Handler: app.lambda_handler` in the `Globals` and leave the `Runtime: python3.7` in the function(s) and vice versa.

**Expected behavior**
One would expect to be able to declare both the Handler and the Runtime inside the Globals [just as in the documentation](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#globals-section) (though they show this for nodejs6.10, so on a Javascript project).

**Screenshots**
<img width="820" alt="handler-broken" src="https://user-images.githubusercontent.com/15079576/57069658-c53cd980-6cc4-11e9-8cb5-ccf9b2c270eb.png">
When only the Handler is put in Globals, it breaks.
<img width="820" alt="runtime-broken" src="https://user-images.githubusercontent.com/15079576/57069646-bbb37180-6cc4-11e9-890f-b6abb6272d8f.png">
When only the Runtime is put in Globals, it breaks.
<img width="820" alt="both-broken" src="https://user-images.githubusercontent.com/15079576/57069634-b0f8dc80-6cc4-11e9-8a49-f752961ba525.png">
When both are put in Globals, it breaks too.
<img width="820" alt="alright" src="https://user-images.githubusercontent.com/15079576/57069612-a2aac080-6cc4-11e9-8b3f-93423449bcfa.png">

When neither of them are put in Globals, it works without exceptions.

**Your Environment**
 - OS: macOS 10.14.4
 - JetBrains' Product: PyCharm 2019.1.1 (Professional Edition)
 - JetBrains' Product Version: Build #PY-191.6605.12, built on April 3, 2019
 - Toolkit Version: 1.3 (2019-04-25)
 - SAM CLI Version: SAM CLI, version 0.14.2
 - JRE: 11.0.2+9-b159.34 x86_64
 - JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 - Python 3.7

**Additional context**
This bug seems to occur in loop since a few seconds after clearing the exception another one with the same details and traceback pops up, and it says the exception occured 11 times since the last clear.

This bug **does not** affect the SAM CLI, as running it with `sam local invoke` doesn't yield any issue.
